/*
 * This source file was generated by the Gradle 'init' task
 */
package testcamera;

// import org.junit.jupiter.api.Test;

// import fr.funecirce.testcamera.Main;

// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     // Main classUnderTest = new Main();
    //     // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
